name: Deploy to static
on:
  push:	
    branches:	
      - master

jobs:
  deploy:
    name: Deploy to static
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'
        # flutter-version: '2.0.5'
    - run: flutter pub get
    # - run: flutter test
    - run: flutter build -v web --release
    - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: static
        FOLDER: build/web/
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
